import { describe, expect, it } from "vitest";
import { parseIniToConfig } from "../src/index.js";

describe("parseIniToConfig · rulesets", () => {
  it("parses geosite / geoip / final / provider ruleset lines with sections", () => {
    const ini = [
      "; Generated by ClashRouteKit",
      "[custom]",
      "; 海外类目",
      "ruleset=AI,[]GEOSITE,openai",
      "ruleset=Proxy,[]GEOIP,telegram,no-resolve",
      "ruleset=Direct,[]GEOIP,cn",
      "ruleset=AI,clash-domain:https://raw.example/x/publish/rules/AI_Domain.yaml,300",
      "ruleset=AI,[]FINAL",
      "ruleset=Proxy,https://raw.example/list/extra.list",
      "",
    ].join("\n");

    const out = parseIniToConfig(ini);

    expect(out.ruleSets).toContainEqual({
      id: "openai",
      section: "海外类目",
      policy: "AI",
      source: { type: "geosite", value: "openai" },
    });
    expect(out.ruleSets.find((r) => r.policy === "Proxy" && r.source.type === "geoip")?.source).toEqual({
      type: "geoip",
      value: "telegram",
      noResolve: true,
    });
    expect(out.ruleSets.find((r) => r.policy === "Direct")?.source).toEqual({
      type: "geoip",
      value: "cn",
      noResolve: false,
    });
    expect(out.ruleSets.find((r) => r.source.type === "rule-provider")?.source).toEqual({
      type: "rule-provider",
      behavior: "domain",
      file: "AI_Domain.yaml",
      interval: 300,
    });
    expect(out.ruleSets.find((r) => r.source.type === "final")).toBeTruthy();
    // 不识别的远程 .list 进 warnings、不进 ruleSets
    expect(out.warnings.some((w) => w.includes("extra.list"))).toBe(true);
  });
});
