import { describe, expect, it } from "vitest";
import { parseIniToConfig } from "../src/index.js";

describe("parseIniToConfig · rulesets", () => {
  it("parses geosite / geoip / final / provider ruleset lines with sections", () => {
    const ini = [
      "; Generated by ClashRouteKit",
      "[custom]",
      "; 海外类目",
      "ruleset=AI,[]GEOSITE,openai",
      "ruleset=Proxy,[]GEOIP,telegram,no-resolve",
      "ruleset=Direct,[]GEOIP,cn",
      "ruleset=AI,clash-domain:https://raw.example/x/publish/rules/AI_Domain.yaml,300",
      "ruleset=AI,[]FINAL",
      "ruleset=Proxy,https://raw.example/list/extra.list",
      "",
    ].join("\n");

    const out = parseIniToConfig(ini);

    expect(out.ruleSets).toContainEqual({
      id: "openai",
      section: "海外类目",
      policy: "AI",
      source: { type: "geosite", value: "openai" },
    });
    expect(out.ruleSets.find((r) => r.policy === "Proxy" && r.source.type === "geoip")?.source).toEqual({
      type: "geoip",
      value: "telegram",
      noResolve: true,
    });
    expect(out.ruleSets.find((r) => r.policy === "Direct")?.source).toEqual({
      type: "geoip",
      value: "cn",
      noResolve: false,
    });
    expect(out.ruleSets.find((r) => r.source.type === "rule-provider")?.source).toEqual({
      type: "rule-provider",
      behavior: "domain",
      file: "AI_Domain.yaml",
      interval: 300,
    });
    expect(out.ruleSets.find((r) => r.source.type === "final")).toBeTruthy();
    // 不识别的远程 .list 进 warnings、不进 ruleSets
    expect(out.warnings.some((w) => w.includes("extra.list"))).toBe(true);
  });

  it("does not leak a comment section to unrelated following rulesets", () => {
    const out = parseIniToConfig(
      [
        "[custom]",
        "; Emby 包括主流 Emby 服务相关域名",
        "ruleset=Emby,[]GEOSITE,category-emby",
        "ruleset=Spotify,[]GEOSITE,spotify",
        "",
      ].join("\n"),
    );

    expect(out.ruleSets).toEqual([
      {
        id: "category-emby",
        section: "Emby 包括主流 Emby 服务相关域名",
        policy: "Emby",
        source: { type: "geosite", value: "category-emby" },
      },
      {
        id: "spotify",
        policy: "Spotify",
        source: { type: "geosite", value: "spotify" },
      },
    ]);
  });
});

describe("parseIniToConfig · proxy groups", () => {
  it("parses select groups (options + node filters)", () => {
    const out = parseIniToConfig("custom_proxy_group=AI`select`[]Proxy`[]DIRECT`.*\n");
    expect(out.customProxyGroups[0]).toEqual({
      name: "AI",
      type: "select",
      options: ["Proxy", "DIRECT"],
      nodeFilters: [".*"],
    });
  });

  it("parses test-type groups with url, interval and tolerance", () => {
    const out = parseIniToConfig(
      "custom_proxy_group=🇭🇰`url-test`!!GROUPID=0!!(港|HK)`https://cp.cloudflare.com/generate_204`300,,50\n",
    );
    expect(out.customProxyGroups[0]).toEqual({
      name: "🇭🇰",
      type: "url-test",
      options: [],
      nodeFilters: ["!!GROUPID=0!!(港|HK)"],
      url: "https://cp.cloudflare.com/generate_204",
      interval: 300,
      timeout: null,
      tolerance: 50,
    });
  });

  it.each([
    ["300", { interval: 300, timeout: null, tolerance: null }],
    ["300,5", { interval: 300, timeout: 5, tolerance: null }],
    ["300,,50", { interval: 300, timeout: null, tolerance: 50 }],
    ["300,5,50", { interval: 300, timeout: 5, tolerance: 50 }],
  ])("parses health-check tail %s", (tail, expected) => {
    const out = parseIniToConfig(
      `custom_proxy_group=Auto\`url-test\`.*\`https://probe.example/204\`${tail}\n`,
    );

    expect(out.customProxyGroups[0]).toMatchObject(expected);
  });
});
