import type { CustomProxyGroup, ImportedConfig, RuleSet, RuleSetSource } from "./types.js";

function basename(url: string): string {
  const noQuery = url.split(/[?#]/)[0];
  const segments = noQuery.split("/").filter(Boolean);
  return segments[segments.length - 1] ?? noQuery;
}

function parseRulesetSource(rest: string): RuleSetSource | { warning: string } {
  if (rest.startsWith("[]GEOSITE,")) {
    return { type: "geosite", value: rest.slice("[]GEOSITE,".length).trim() };
  }
  if (rest.startsWith("[]GEOIP,")) {
    const parts = rest.slice("[]GEOIP,".length).split(",").map((part) => part.trim());
    return { type: "geoip", value: parts[0], noResolve: parts.includes("no-resolve") };
  }
  if (rest === "[]FINAL") {
    return { type: "final" };
  }
  const provider = /^clash-(domain|classic|ipcidr):(.+),(\d+)\s*$/.exec(rest);
  if (provider) {
    const behavior =
      provider[1] === "domain" ? "domain" : provider[1] === "classic" ? "classical" : "ipcidr";
    return { type: "rule-provider", behavior, file: basename(provider[2]), interval: Number(provider[3]) };
  }
  return { warning: `无法识别的 ruleset 源：${rest}` };
}

export function parseIniToConfig(ini: string): ImportedConfig {
  const customProxyGroups: CustomProxyGroup[] = [];
  const ruleSets: RuleSet[] = [];
  const warnings: string[] = [];
  const usedIds = new Set<string>();
  let currentSection: string | undefined;

  const uniqueId = (base: string): string => {
    let id = base || "rule";
    let counter = 1;
    while (usedIds.has(id)) id = `${base}-${counter++}`;
    usedIds.add(id);
    return id;
  };

  for (const rawLine of ini.replace(/\r\n?/g, "\n").split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith(";") || line.startsWith("#")) {
      const text = line.replace(/^[;#]\s*/, "").trim();
      if (text && !/^Generated by/i.test(text)) currentSection = text;
      continue;
    }
    if (line.startsWith("[") && line.endsWith("]")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1);

    if (key === "ruleset") {
      const comma = value.indexOf(",");
      if (comma === -1) {
        warnings.push(`ruleset 缺少策略：${value}`);
        continue;
      }
      const policy = value.slice(0, comma).trim();
      const parsed = parseRulesetSource(value.slice(comma + 1).trim());
      if ("warning" in parsed) {
        warnings.push(parsed.warning);
        continue;
      }
      const base =
        parsed.type === "geosite"
          ? parsed.value
          : parsed.type === "geoip"
            ? `geoip-${parsed.value}`
            : parsed.type === "rule-provider"
              ? parsed.file.replace(/\.[^.]+$/, "")
              : "final";
      const ruleSet: RuleSet = { id: uniqueId(base), policy, source: parsed };
      if (currentSection) ruleSet.section = currentSection;
      ruleSets.push(ruleSet);
    }
  }

  return { customProxyGroups, ruleSets, warnings };
}
