import type { CustomProxyGroup, ImportedConfig, RuleSet, RuleSetSource } from "./types.js";

function basename(url: string): string {
  const noQuery = url.split(/[?#]/)[0];
  const segments = noQuery.split("/").filter(Boolean);
  return segments[segments.length - 1] ?? noQuery;
}

function parseRulesetSource(rest: string): RuleSetSource | { warning: string } {
  if (rest.startsWith("[]GEOSITE,")) {
    return { type: "geosite", value: rest.slice("[]GEOSITE,".length).trim() };
  }
  if (rest.startsWith("[]GEOIP,")) {
    const parts = rest.slice("[]GEOIP,".length).split(",").map((part) => part.trim());
    return { type: "geoip", value: parts[0], noResolve: parts.includes("no-resolve") };
  }
  if (rest === "[]FINAL") {
    return { type: "final" };
  }
  const provider = /^clash-(domain|classic|ipcidr):(.+),(\d+)\s*$/.exec(rest);
  if (provider) {
    const behavior =
      provider[1] === "domain" ? "domain" : provider[1] === "classic" ? "classical" : "ipcidr";
    return { type: "rule-provider", behavior, file: basename(provider[2]), interval: Number(provider[3]) };
  }
  return { warning: `无法识别的 ruleset 源：${rest}` };
}

const GROUP_TYPES = new Set(["select", "url-test", "fallback", "load-balance"]);

function parseProxyGroupLine(body: string, warnings: string[]): CustomProxyGroup | null {
  const parts = body.split("`");
  if (parts.length < 2) {
    warnings.push(`策略组格式不全：${body}`);
    return null;
  }
  const [name, type, ...rest] = parts;
  if (!GROUP_TYPES.has(type)) {
    warnings.push(`未知策略组类型：${type}`);
    return null;
  }
  const groupType = type as CustomProxyGroup["type"];

  let url: string | undefined;
  let interval: number | undefined;
  let timeout: number | null | undefined;
  let tolerance: number | null | undefined;
  let refsAndFilters = rest;
  if (groupType !== "select" && rest.length >= 2) {
    const intervalSpec = rest[rest.length - 1];
    url = rest[rest.length - 2];
    refsAndFilters = rest.slice(0, rest.length - 2);
    const segments = intervalSpec.split(",");
    timeout = null;
    tolerance = null;
    const parsedInterval = Number(segments[0]);
    if (!Number.isNaN(parsedInterval)) interval = parsedInterval;
    if (segments[1] !== undefined && segments[1] !== "") {
      const parsedTimeout = Number(segments[1]);
      if (!Number.isNaN(parsedTimeout)) timeout = parsedTimeout;
    }
    if (segments[2] !== undefined && segments[2] !== "") {
      const parsedTolerance = Number(segments[2]);
      if (!Number.isNaN(parsedTolerance)) tolerance = parsedTolerance;
    }
  }

  const options: string[] = [];
  const nodeFilters: string[] = [];
  for (const item of refsAndFilters) {
    if (item.startsWith("[]")) options.push(item.slice(2));
    else nodeFilters.push(item);
  }

  const group: CustomProxyGroup = { name, type: groupType, options };
  if (nodeFilters.length > 0) group.nodeFilters = nodeFilters;
  if (url) group.url = url;
  if (interval !== undefined) group.interval = interval;
  if (timeout !== undefined) group.timeout = timeout;
  if (tolerance !== undefined) group.tolerance = tolerance;
  return group;
}

export function parseIniToConfig(ini: string): ImportedConfig {
  const customProxyGroups: CustomProxyGroup[] = [];
  const ruleSets: RuleSet[] = [];
  const warnings: string[] = [];
  const usedIds = new Set<string>();
  let currentSection: string | undefined;

  const uniqueId = (base: string): string => {
    let id = base || "rule";
    let counter = 1;
    while (usedIds.has(id)) id = `${base}-${counter++}`;
    usedIds.add(id);
    return id;
  };

  for (const rawLine of ini.replace(/\r\n?/g, "\n").split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    if (line.startsWith(";") || line.startsWith("#")) {
      const text = line.replace(/^[;#]\s*/, "").trim();
      if (text && !/^Generated by/i.test(text)) currentSection = text;
      continue;
    }
    if (line.startsWith("[") && line.endsWith("]")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1);

    if (key === "ruleset") {
      const comma = value.indexOf(",");
      if (comma === -1) {
        warnings.push(`ruleset 缺少策略：${value}`);
        continue;
      }
      const policy = value.slice(0, comma).trim();
      const parsed = parseRulesetSource(value.slice(comma + 1).trim());
      if ("warning" in parsed) {
        warnings.push(parsed.warning);
        continue;
      }
      const base =
        parsed.type === "geosite"
          ? parsed.value
          : parsed.type === "geoip"
            ? `geoip-${parsed.value}`
            : parsed.type === "rule-provider"
              ? parsed.file.replace(/\.[^.]+$/, "")
              : "final";
      const ruleSet: RuleSet = { id: uniqueId(base), policy, source: parsed };
      if (currentSection) ruleSet.section = currentSection;
      ruleSets.push(ruleSet);
      currentSection = undefined;
    } else if (key === "custom_proxy_group") {
      const group = parseProxyGroupLine(value, warnings);
      if (group) customProxyGroups.push(group);
    }
  }

  return { customProxyGroups, ruleSets, warnings };
}
