import type { CustomProxyGroup, ProviderBehavior, RenderIniOptions, RouteKitConfig, RuleSet } from "./types.js";

function providerKind(behavior: ProviderBehavior): string {
  if (behavior === "domain") return "clash-domain";
  if (behavior === "classical") return "clash-classic";
  if (behavior === "ipcidr") return "clash-ipcidr";
  throw new Error(`Unsupported provider behavior: ${behavior satisfies never}`);
}

function publishRulesUrl(baseUrl: string, file: string): string {
  return `${baseUrl.replace(/\/+$/, "")}/rules/${file}`;
}

function renderRuleSet(ruleSet: RuleSet, publishBaseUrl: string): string[] {
  if (ruleSet.enabled === false) return [];

  const source = ruleSet.source;
  if (source.type === "rule-provider") {
    return [
      `ruleset=${ruleSet.policy},${providerKind(source.behavior)}:${publishRulesUrl(
        publishBaseUrl,
        source.file,
      )},${source.interval ?? 28800}`,
    ];
  }
  if (source.type === "geosite") {
    return [`ruleset=${ruleSet.policy},[]GEOSITE,${source.value}`];
  }
  if (source.type === "geoip") {
    return [
      `ruleset=${ruleSet.policy},[]GEOIP,${source.value}${source.noResolve !== false ? ",no-resolve" : ""}`,
    ];
  }
  if (source.type === "final") {
    return [`ruleset=${ruleSet.policy},[]FINAL`];
  }

  const unsupported: never = source;
  throw new Error(`Unsupported ruleSet source: ${String(unsupported)}`);
}

function renderCustomProxyGroup(group: CustomProxyGroup): string {
  const optionRefs = group.options.map((option) => `[]${option}`);
  const options = [...optionRefs, ...(group.nodeFilters ?? [])].join("`");
  if (group.type === "select") {
    return `custom_proxy_group=${group.name}\`select\`${options}`;
  }

  const url = group.url ?? "https://cp.cloudflare.com/generate_204";
  const interval = group.interval ?? 300;
  const tolerance = group.tolerance ?? 50;
  return `custom_proxy_group=${group.name}\`${group.type}\`${options}\`${url}\`${interval},,${tolerance}`;
}

export function renderIni(config: RouteKitConfig, options: RenderIniOptions = {}): string {
  const ruleLines = config.ruleSets.flatMap((ruleSet) =>
    renderRuleSet(ruleSet, config.publishBaseUrl),
  );

  const groupLines = config.customProxyGroups.map(renderCustomProxyGroup);

  const tail: string[] = [];
  if (options.clashRuleBase) {
    tail.push(`clash_rule_base=${options.clashRuleBase}`);
  }
  tail.push(`enable_rule_generator=${options.enableRuleGenerator ?? true}`);
  tail.push(`overwrite_original_rules=${options.overwriteOriginalRules ?? true}`);

  return [
    "; Generated by ClashRouteKit",
    "[custom]",
    "",
    ...ruleLines,
    "",
    ...groupLines,
    "",
    ...tail,
    "",
  ].join("\n");
}
