import type { ProviderReference, ProxyGroup, RouteKitConfig, RouteModule } from "./types.js";

function providerKind(behavior: ProviderReference["behavior"]): string {
  if (behavior === "domain") return "clash-domain";
  if (behavior === "classical") return "clash-classic";
  if (behavior === "ipcidr") return "clash-ipcidr";
  throw new Error(`Unsupported provider behavior: ${behavior satisfies never}`);
}

function publishRulesUrl(baseUrl: string, file: string): string {
  return `${baseUrl.replace(/\/+$/, "")}/rules/${file}`;
}

function renderModuleRules(module: RouteModule, publishBaseUrl: string): string[] {
  if (module.enabled === false) return [];

  const lines: string[] = [];
  for (const provider of module.providers ?? []) {
    lines.push(
      `ruleset=${module.policy},${providerKind(provider.behavior)}:${publishRulesUrl(
        publishBaseUrl,
        provider.file,
      )},${provider.interval ?? 28800}`,
    );
  }
  for (const tag of module.geosite ?? []) {
    lines.push(`ruleset=${module.policy},[]GEOSITE,${tag}`);
  }
  for (const tag of module.geoip ?? []) {
    lines.push(`ruleset=${module.policy},[]GEOIP,${tag},no-resolve`);
  }
  return lines;
}

function renderProxyGroup(group: ProxyGroup): string {
  const optionRefs = group.options.map((option) => `[]${option}`);
  const options = [...optionRefs, ...(group.nodeFilters ?? [])].join("`");
  if (group.type === "select") {
    return `custom_proxy_group=${group.name}\`select\`${options}`;
  }

  const url = group.url ?? "https://cp.cloudflare.com/generate_204";
  const interval = group.interval ?? 300;
  const tolerance = group.tolerance ?? 50;
  return `custom_proxy_group=${group.name}\`${group.type}\`${options}\`${url}\`${interval},,${tolerance}`;
}

export function renderIni(config: RouteKitConfig): string {
  const ruleLines = config.modules.flatMap((module) =>
    renderModuleRules(module, config.publishBaseUrl),
  );
  ruleLines.push(`ruleset=${config.final.policy},[]FINAL`);

  const groupLines = config.proxyGroups.map(renderProxyGroup);

  return [
    "; Generated by ClashRouteKit",
    "[custom]",
    "",
    ...ruleLines,
    "",
    ...groupLines,
    "",
    "enable_rule_generator=true",
    "overwrite_original_rules=true",
    "",
  ].join("\n");
}
