import {
  resolveGeoipNoResolve,
  resolveProxyGroupHealthCheck,
  resolveRuleProviderInterval,
} from "./defaults.js";
import type {
  CustomProxyGroup,
  ProviderBehavior,
  RenderIniOptions,
  RouteKitConfig,
  RouteKitDefaults,
  RuleSet,
} from "./types.js";

function providerKind(behavior: ProviderBehavior): string {
  if (behavior === "domain") return "clash-domain";
  if (behavior === "classical") return "clash-classic";
  if (behavior === "ipcidr") return "clash-ipcidr";
  throw new Error(`Unsupported provider behavior: ${behavior satisfies never}`);
}

function publishRulesUrl(baseUrl: string, file: string): string {
  return `${baseUrl.replace(/\/+$/, "")}/rules/${file}`;
}

function renderRuleSet(
  ruleSet: RuleSet,
  publishBaseUrl: string,
  defaults?: RouteKitDefaults,
): string[] {
  if (ruleSet.enabled === false) return [];

  const source = ruleSet.source;
  if (source.type === "rule-provider") {
    return [
      `ruleset=${ruleSet.policy},${providerKind(source.behavior)}:${publishRulesUrl(
        publishBaseUrl,
        source.file,
      )},${resolveRuleProviderInterval(source, defaults).value}`,
    ];
  }
  if (source.type === "geosite") {
    return [`ruleset=${ruleSet.policy},[]GEOSITE,${source.value}`];
  }
  if (source.type === "geoip") {
    const noResolve = resolveGeoipNoResolve(source, defaults).value;
    return [
      `ruleset=${ruleSet.policy},[]GEOIP,${source.value}${noResolve ? ",no-resolve" : ""}`,
    ];
  }
  if (source.type === "final") {
    return [`ruleset=${ruleSet.policy},[]FINAL`];
  }

  const unsupported: never = source;
  throw new Error(`Unsupported ruleSet source: ${String(unsupported)}`);
}

function renderHealthCheckTail(
  interval: number,
  timeout: number | undefined,
  tolerance: number | undefined,
): string {
  if (tolerance !== undefined) return `${interval},${timeout ?? ""},${tolerance}`;
  if (timeout !== undefined) return `${interval},${timeout}`;
  return String(interval);
}

function renderCustomProxyGroup(
  group: CustomProxyGroup,
  defaults?: RouteKitDefaults,
): string {
  const optionRefs = group.options.map((option) => `[]${option}`);
  const options = [...optionRefs, ...(group.nodeFilters ?? [])].join("`");
  if (group.type === "select") {
    return `custom_proxy_group=${group.name}\`select\`${options}`;
  }

  const healthCheck = resolveProxyGroupHealthCheck(group, defaults);
  const url = healthCheck.url.value!;
  const interval = healthCheck.interval.value!;
  const tail = renderHealthCheckTail(
    interval,
    healthCheck.timeout.value,
    healthCheck.tolerance.value,
  );
  return `custom_proxy_group=${group.name}\`${group.type}\`${options}\`${url}\`${tail}`;
}

export function renderIni(config: RouteKitConfig, options: RenderIniOptions = {}): string {
  const ruleLines: string[] = [];
  let lastSection: string | undefined;
  for (const ruleSet of config.ruleSets) {
    if (ruleSet.enabled === false) continue;
    if (ruleSet.section && ruleSet.section !== lastSection) {
      ruleLines.push(`; ${ruleSet.section}`);
      lastSection = ruleSet.section;
    }
    ruleLines.push(...renderRuleSet(ruleSet, config.publishBaseUrl, config.defaults));
  }

  const groupLines = config.customProxyGroups.map((group) =>
    renderCustomProxyGroup(group, config.defaults),
  );

  const tail: string[] = [];
  if (options.clashRuleBase) {
    tail.push(`clash_rule_base=${options.clashRuleBase}`);
  }
  tail.push(`enable_rule_generator=${options.enableRuleGenerator ?? true}`);
  tail.push(`overwrite_original_rules=${options.overwriteOriginalRules ?? true}`);

  return [
    "; Generated by ClashRouteKit",
    "[custom]",
    "",
    ...ruleLines,
    "",
    ...groupLines,
    "",
    ...tail,
    "",
  ].join("\n");
}
