import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { importIni } from "../src/program.js";

describe("CLI importIni", () => {
  it("parses a SubConverter INI into a scaffold routes config", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "route-kit-import-"));
    const ini = [
      "; Generated by ClashRouteKit",
      "[custom]",
      "; 海外类目",
      "ruleset=AI,[]GEOSITE,openai",
      "ruleset=AI,[]FINAL",
      "custom_proxy_group=AI`select`[]DIRECT",
      "enable_rule_generator=true",
      "",
    ].join("\n");
    await writeFile(path.join(root, "in.ini"), ini, "utf8");

    const result = await importIni({ root, configFile: "routes.yaml", iniFile: "in.ini" });

    expect(result.ruleSets.find((r) => r.source.type === "geosite")?.source).toEqual({
      type: "geosite",
      value: "openai",
    });
    expect(result.customProxyGroups).toEqual([{ name: "AI", type: "select", options: ["DIRECT"] }]);

    const scaffold = await readFile(result.scaffoldPath, "utf8");
    expect(scaffold).toContain("value: openai");
    expect(scaffold).toContain("publishBaseUrl:");
  });
});
